<?php

namespace Raindrop\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    public function findOneByPageAndName($page, $name)
    {
        $q =
            $this->createQueryBuilder('b')
            ->where('b.page = :page AND b.name = :name')
            ->setParameter('page', $page->getId())
            ->setParameter('name', $name)
        ;

        return $q->getQuery()->getOneOrNullResult();
    }
}
