<?php

namespace Raindrop\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockVariableRepository extends EntityRepository
{
    public function findOnyByNameAndBlock($name, $block) {
        $q = $this->createQueryBuilder('q')
                ->where('q.name = :name AND q.block = :block')
                ->setParameters(array(
                    ':name' => $name,
                    ':block' => $block
                ))
                ;
        return $q->getQuery()->getOneOrNullResult();
    }
}
