<?php

namespace Raindrop\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function findOneByMenuAndPage($page, $menu)
    {
        $query = $this->repository->createQueryBuilder('m')
            ->select('m')
            ->where('m.page = :page AND m.menu = :menu')
            ->setParameters(array(
                'page' => $page,
                'menu' => $menu
            ))
        ;

        return $query->getQuery()->getResult();
    }
}
